[project]
name = "analytics-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "clickhouse-connect>=0.8.0",
    "fastapi[standard]>=0.136.0",
    "pydantic-settings>=2.13.1",
    "pydantic[email]>=2.13.1",
    "python-dotenv>=1.2.2",
    "uvicorn>=0.44.0",
]
